### PR TITLE
compute over batched transaction list

### LINKED ISSUE #2520: [ergo] Can we fix dust mining issue? Out of memory error
Can we fix dust mining issue. I have over 300 transactions in one address and now the wallet grind to a halt. I can't do anything. I can't even send all the assets to a new address.

It looks like it is caused by this error on the console:
```
ErgoApi::refreshTransactions error: "out of memory"
```

### PR DESCRIPTION
**Pull request by yushih**
Currently when the wallet transaction list is periodically refreshed, some data are computed over the full transaction list. Previously, #2561 makes it so that the full transaction list doesn't need to be kept in memory after the computation. This PR further optimizes the process so that at any time, only a constant-sized portion of the full transaction list are loaded from the storage layer.

### CODE REVIEW

File: packages/yoroi-extension/app/stores/toplevel/TransactionsStore.js [hunk 1]
```diff
@@ -543,27 +546,50 @@ export default class TransactionsStore extends Store<StoresMap, ActionsMap> {
...
+        new TotalAvailableReducer(),
+        new UnconfirmedAmountReducer(
+          txRequests.lastSyncInfo.Height,
+          assuranceMode,
+          getUnitOfAccount,
+          defaultTokenInfo,
+        ),
+        new RemoteTransactionIdsReducer(),
+        new TimestampsReducer()
+      ];
```
Comment (zuzunker) [inline packages/yoroi-extension/app/stores/toplevel/TransactionsStore.js:562]: Nice

**Review by zuzunker — APPROVED** [review]

**Review by zuzunker — COMMENTED** [review]
/check
