### PR TITLE
[4.7.500] Reworked the reward amount parsing a bit

### LINKED ISSUE #2522: Yoroi extension on Chrome is stuck with white screen on launch
・ Yoroi Chrome version is 4.7.4
・ OS: Macbook (other user has reported on different OS too, see forum link below)
・ User has lost his recovery phrase and is dependent on his spending password to create new wallet or attempt any reinstalls
・ Not a unique case (few users have reported it before, eg: [here](https://forum.cardano.org/t/yoroi-blank-page-after-alonzo-upgrade/78978))
・ The behaviour has been present for months
・ Console Error:
```
618.bundle.js:1 rolling back Lovefield query for
KeyDerivation
Address
AddressMapping
EncryptionMeta
UtxoTransactionInput
UtxoTransactionOutput
TokenList
Token
CertificateAddress
Certificate
Transaction
Block
AccountingTransactionInput
AccountingTransactionOutput
RootDerivation
PurposeDerivation
CoinTypeDerivation
Bip44Account
Bip44Chain
CanonicalAddress with error {}
N @ 618.bundle.js:1
yoroi_bde52cb3.bundle.js:1 AdaApi::refreshTransactions error: {
  "stack": "Error: [BigNumber Error] Not a number: undefined
    at i (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/46.bundle.js:2:53381)
    at new W (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/46.bundle.js:2:44480)
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/544.bundle.js:1:1281533
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/544.bundle.js:1:1281597
    at Array.map (<anonymous>)
    at he (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/544.bundle.js:1:1280437)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/544.bundle.js:1:1282152
    at async N (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:45470)
    at async me (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/544.bundle.js:1:1282058)
    at async Te.refreshTransactions (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:2308)",
  "message": "[BigNumber Error] Not a number: undefined"
}
error @ yoroi_bde52cb3.bundle.js:1
yoroi_bde52cb3.bundle.js:1 WalletStore::refreshWalletFromLocalOnLaunch {
  "message": "api.errors.GenericApiError: undefined",
  "name": "l",
  "stack": "l: api.errors.GenericApiError: undefined
    at Te.refreshTransactions (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:3111)
    at async i._method (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_ef4bde61.bundle.js:1:145790)",
  "id": "api.errors.GenericApiError",
  "defaultMessage": "!!!An error occurred, please try again later.",
  "values": {}
}
error @ yoroi_bde52cb3.bundle.js:1
yoroi_ef4bde61.bundle.js:1 Uncaught (in promise) l
```

### PR DESCRIPTION
**Pull request by zuzunker**

### CODE REVIEW

File: packages/yoroi-extension/app/api/ada/lib/storage/bridge/updateTransactions.js [hunk 1]
```diff
@@ -371,10 +371,13 @@ export async function rawGetTransactions(
...
                   // happens if the MIR is to another pot
                   if (rewardAmount == null) continue;
+                  const rewardAmountStr = rewardAmount.is_positive()
+                    ? rewardAmount.as_positive().to_str()
+                    : ('-' + rewardAmount.as_negative().to_str());
                   implicitOutputSum.add({
                     identifier: defaultToken.defaultIdentifier,
                     networkId: defaultToken.defaultNetworkId,
-                    amount: new BigNumber(String(rewardAmount.as_i32())),
+                    amount: new BigNumber(rewardAmountStr),
```
Comment (zuzunker) [inline packages/yoroi-extension/app/api/ada/lib/storage/bridge/updateTransactions.js:384]: The problem that is being solved here is that Rust type `Int` from the serialization-lib wraps an `i128` and so can be a positive or a negative big number. Previously it was calling `as_i32()` which might return an `undefined` in case the i128 value is out of the i32 bounds, the error is silently ignorred (which was not a great decision).

The Rust type `BigInt` from the serialisation-lib wraps a `u64` value so can only hold positive integer numbers. This is why `Int` implements these weird methods for `.is_positive` , `.as_positive` , and `.as_negative` . We have to work around this conversion from a signed to an unsigned type but it is much more secure about the value size boundaries.

For the next serlib version there will be a new method `Int::to_str` which will return the string with a positive or negative value directly.

**Review by yushih — DISMISSED** [review]
LGTM. +1 for adding `Int::to_str`.

**Review by zuzunker — COMMENTED** [review]
/check

**Comment by zuzunker** [comment]
Release: https://github.com/Emurgo/yoroi-frontend/releases/tag/4.7.500
