### PR TITLE
Ruslan / Update Rust dependency

### LINKED ISSUE #33: Invalid Witness on wallet recovery
> I entered the recovery phrase, then go to the screen with the addresses,recovered balance, final balance, etc. which all seemed correct. Then when I clicked the transfer funds button on that screen it just said "Unable to transfer funds"

```
[2018-10-09T18:26:07-04:00] yoroi-backend-api::sendTx error: {
  "stack": "Error: Request failed with status code 400\n    at createError (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/vendor.js:44798:15)\n    at settle (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/vendor.js:87142:12)\n    at XMLHttpRequest.handleLoad (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/vendor.js:44671:7)",
  "message": "Request failed with status code 400",
  "config": {},
  "request": {
    "response": "{\"code\":\"InvalidContent\",\"message\":\"Invalid witness\"}"
  },
  "response": {
    "config": {},
    "request": {
      "response": "{\"code\":\"InvalidContent\",\"message\":\"Invalid witness\"}"
    }
  }
}
[2018-10-09T18:26:07-04:00] DaedalusTransferStore::transferFunds {
  "message": "api.errors.invalidWitnessError: {}",
  "name": "t",
  "stack": "t: api.errors.invalidWitnessError: {}\n    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi.bundle.js:1:46978",
  "id": "api.errors.invalidWitnessError",
  "defaultMessage": "!!!The signature is invalid.",
  "values": {}
}
```

### PR DESCRIPTION
**Pull request by vantuz-subhuman**
Updated the `js-cardano-wasm` submodule to the latest known stable for us version, with updated `rust-cardano` that has some very important fixes

Closes #33

### CODE REVIEW

**Comment by vantuz-subhuman** [comment]
@nicarq, @SebastienGllmt, ready to review and merge

File: setup_cardano_crypto.sh [hunk 1]
```diff
@@ -2,10 +2,8 @@
 
 git submodule update --init --recursive && \
 cd js-cardano-wasm && \
-git checkout def5d9a0ebd69435d29e737c7e99ea04f692ab70 && \
-cd rust && \
-git checkout 8b441cbbeba32ada20d065399083a16d85a5fe29 && \
-cd .. && \
+git checkout 386cc1ebe9cba1a1bf90304a491221d6986cd865 && \
```
Comment (nicarq) [inline setup_cardano_crypto.sh]: can we keep the checkout for rust plz I would prefer to be deterministic to a specific commit like `f8d7ac102b569f8198f227029cf190c084554ba8` (latest one on this moment in master)
